// Generated by vite-plugin-svg-spritemap
export type Prefix = 'icon-';

export type Icons = 'CH' | 'FR' | 'JP' | 'no_viewbox' | 'spiriit' | 'vite';
export type IconsPrefixed = `${Prefix}${Icons}`;

export type UiIcons = 'no_viewbox' | 'spiriit' | 'vite';
export type UiIconsPrefixed = `${Prefix}${UiIcons}`;

export type Flags = 'CH' | 'FR' | 'JP';
export type FlagsPrefixed = `${Prefix}${Flags}`;
