catalogMode: strict

minimumReleaseAgeExclude:
  - tsdown@0.22.12
  - verkit@0.1.0
  - '@nuxt/kit@4.5.1'
  - '@nuxt/nitro-server@4.5.1'
  - '@nuxt/schema@4.5.1'
  - '@nuxt/vite-builder@4.5.1'
  - '@rollup/rollup-android-arm-eabi@4.62.3'
  - '@rollup/rollup-android-arm64@4.62.3'
  - '@rollup/rollup-darwin-arm64@4.62.3'
  - '@rollup/rollup-darwin-x64@4.62.3'
  - '@rollup/rollup-freebsd-arm64@4.62.3'
  - '@rollup/rollup-freebsd-x64@4.62.3'
  - '@rollup/rollup-linux-arm-gnueabihf@4.62.3'
  - '@rollup/rollup-linux-arm-musleabihf@4.62.3'
  - '@rollup/rollup-linux-arm64-gnu@4.62.3'
  - '@rollup/rollup-linux-arm64-musl@4.62.3'
  - '@rollup/rollup-linux-loong64-gnu@4.62.3'
  - '@rollup/rollup-linux-loong64-musl@4.62.3'
  - '@rollup/rollup-linux-ppc64-gnu@4.62.3'
  - '@rollup/rollup-linux-ppc64-musl@4.62.3'
  - '@rollup/rollup-linux-riscv64-gnu@4.62.3'
  - '@rollup/rollup-linux-riscv64-musl@4.62.3'
  - '@rollup/rollup-linux-s390x-gnu@4.62.3'
  - '@rollup/rollup-linux-x64-gnu@4.62.3'
  - '@rollup/rollup-linux-x64-musl@4.62.3'
  - '@rollup/rollup-openbsd-x64@4.62.3'
  - '@rollup/rollup-openharmony-arm64@4.62.3'
  - '@rollup/rollup-win32-arm64-msvc@4.62.3'
  - '@rollup/rollup-win32-ia32-msvc@4.62.3'
  - '@rollup/rollup-win32-x64-gnu@4.62.3'
  - '@rollup/rollup-win32-x64-msvc@4.62.3'
  - nuxt@4.5.1
  - rollup@4.62.3
  - less@4.8.1
  - svelte-check@4.7.4 || 4.7.6
  - svg-element-attributes@2.2.0
  - '@xmldom/xmldom@0.9.11'
  - svelte@5.56.9
shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@5.7.2 || 6.3.1
  - chokidar@4.0.3

packages:
  - demo/*

catalog:
  '@antfu/eslint-config': 9.3.0
  '@oxvg/napi': 0.0.7
  '@sveltejs/adapter-auto': ^7.0.1
  '@sveltejs/kit': ^2.70.2
  '@sveltejs/vite-plugin-svelte': ^7.3.0
  '@tsconfig/svelte': ^5.0.8
  '@types/less': ^3.0.8
  '@types/node': ^24.13.3
  '@types/picomatch': ^4.0.3
  '@types/stylus': ^0.48.43
  '@vitejs/plugin-vue': ^6.0.8
  '@vitest/coverage-v8': ^4.1.10
  '@xmldom/xmldom': ^0.9.11
  autoprefixer: ^10.5.4
  concurrently: ^10.0.4
  eslint: ^10.8.1
  kolorist: ^1.8.0
  less: ^4.8.1
  mini-svg-data-uri: ^1.4.4
  nitropack: ^2.13.4
  nuxt: ^4.5.2
  picomatch: ^4.0.5
  playwright: ^1.62.1
  postcss: ^8.5.26
  pug: ^3.0.4
  rollup: ^4.62.4
  sass: ^1.102.0
  stylus: ^0.64.0
  svelte: ^5.56.9
  svelte-check: ^4.7.6
  svg-element-attributes: ^2.2.0
  svgo: ^4.0.2
  tinyglobby: ^0.2.17
  tsdown: ^0.22.14
  tslib: ^2.8.1
  typescript: ^6.0.3
  vite: ^7.3.6
  vite-plugin-inspect: ^12.0.2
  vitepress: ^2.0.0-alpha.19
  vitest: ^4.1.10
  vue: ^3.5.41
  vue-router: ^5.2.0
  vue-tsc: ^3.3.9

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - less

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
