shellEmulator: true

trustPolicy: no-downgrade

packages:
  - demo/*

catalog:
  '@sveltejs/vite-plugin-svelte': ^7.0.0
  '@vitejs/plugin-vue': ^6.0.3
  autoprefixer: ^10.4.27
  postcss: ^8.5.8
  sass: ^1.98.0
  stylus: ^0.64.0
  svelte: ^5.55.1
  svelte-check: ^4.4.6
  tslib: ^2.8.1
  typescript: ^6.0.2
  vite: ^7.3.1
  vite-plugin-inspect: ^11.3.3
  vue: ^3.5.31

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - less
