import { readFile } from 'fs'
import { promisify } from 'util'
import { join } from 'path'
import svgToMiniDataURI from 'mini-svg-data-uri'
import { StylesLang, SvgMapObject } from '../types'

interface SvgDataUriMapObject {
  width: number
  height: number
  viewbox: number[]
  svgDataUri?: string
}

export class Styles {
  private _svgs: Map<string, SvgDataUriMapObject>
  private _lang: StylesLang

  constructor(svgs: Map<string, SvgMapObject>, lang: StylesLang) {
    this._svgs = new Map()
    this._lang = lang

    svgs.forEach((svg, name) => {
      const svgDataUri = svgToMiniDataURI(svg.source)

      this._svgs.set(name, {
        width: svg.width,
        height: svg.height,
        viewbox: svg.viewBox,
        svgDataUri
      })
    })
  }

  protected createSpriteMap(
    generator: (
      name: string,
      svg: SvgDataUriMapObject,
      isLast: boolean
    ) => string
  ): string {
    let spriteMap = ''
    let index = 1
    this._svgs.forEach((svg, name) => {
      spriteMap += `${generator(name, svg, index === this._svgs.size)}\n`
      index++
    })
    return spriteMap
  }

  private async insert(insert: string): Promise<string> {
    const template = await promisify(readFile)(
      join(__dirname, `/template.${this._lang}`),
      'utf8'
    )

    const doNotEditThisFile = '// Generated by vite-plugin-svg-spritemap\n\n'
    const prettierIgnore = '/* prettier-ignore */\n'

    return (
      doNotEditThisFile +
      prettierIgnore +
      insert +
      '\n' +
      prettierIgnore +
      template
    )
  }

  // SCSS generation
  private _generate_scss() {
    let insert = '$sprites: (\n'
    insert += this.createSpriteMap((name, svg, isLast) => {
      let sprites = ''
      sprites = `\t'${name}': (`
      sprites += `\n\t\turi: "${svg.svgDataUri}",`
      sprites += `\n\t\twidth: ${svg.width}px,`
      sprites += `\n\t\theight: ${svg.height}px`
      sprites += `\n\t${!isLast ? '),' : ')'}`
      return sprites
    })
    insert += ');\n'

    return insert
  }

  // Styl generation
  private _generate_styl() {
    let insert = '$sprites = {\n'
    insert += this.createSpriteMap((name, svg, isLast) => {
      let sprites = ''
      sprites = `\t'${name}': {`
      sprites += `\n\t\turi: "${svg.svgDataUri}",`
      sprites += `\n\t\twidth: ${svg.width}px,`
      sprites += `\n\t\theight: ${svg.height}px`
      sprites += `\n\t${!isLast ? '},' : '}'}`
      return sprites
    })
    insert += '}\n'

    return insert
  }

  // Less generation
  private _generate_less() {
    let insert = '@sprites: {\n'
    insert += this.createSpriteMap((name, svg) => {
      let sprites = ''
      sprites = `\t@${name}: {`
      sprites += `\n\t\turi: "${svg.svgDataUri}";`
      sprites += `\n\t\twidth: ${svg.width}px;`
      sprites += `\n\t\theight: ${svg.height}px;`
      sprites += `\n\t};`
      return sprites
    })
    insert += '};\n'

    return insert
  }

  public async generate(): Promise<string> {
    let insert: string
    switch (this._lang) {
      case 'scss':
        insert = this._generate_scss()
        break
      case 'styl':
        insert = this._generate_styl()
        break
      case 'less':
        insert = this._generate_less()
        break
      default:
        insert = ''
    }
    return this._lang === 'css'
      ? await new Promise(() => {
          return insert
        })
      : await this.insert(insert)
  }
}
