// Generated by vite-plugin-svg-spritemap
/**
 * Prefix: 'icon-'
 */

export type Icons = 'no_viewbox' | 'no_width_height' | 'spiriit' | 'vite';
export type IconsPrefix = 'icon-';
export type IconsPrefixed = `${IconsPrefix}${Icons}`;
