// Generated by vite-plugin-svg-spritemap
/**
 * Prefix: none
 */

export type Icons = 'no_viewbox' | 'no_width_height' | 'spiriit' | 'vite';
export type IconsPrefix = '';
export type IconsPrefixed = `${IconsPrefix}${Icons}`;
