// Generated by vite-plugin-svg-spritemap
/**
 * Prefix: 'sprite-'
 */

export type Icons = 'custom-no_viewbox' | 'custom-no_width_height' | 'custom-spiriit' | 'custom-vite';
export type IconsPrefix = 'sprite-';
export type IconsPrefixed = `${IconsPrefix}${Icons}`;
