import type { Glob } from 'picomatch'
import type { Options, SvgMapObject } from '@/types'
import { resolve } from 'node:path'
import picomatch from 'picomatch'
import { normalizePath } from 'vite'

interface IconEntry {
  id: string
  /** Icon file path, normalized to forward slashes so picomatch can match it. */
  posixPath: string
}

const ICONS_TYPE = 'Icons'
const PREFIX_TYPE = 'Prefix'

/**
 * Top-level type names the generator always emits. Group names must not collide
 * with these, so the options validation checks against this list.
 */
export const RESERVED_TYPE_NAMES: readonly string[] = [ICONS_TYPE, PREFIX_TYPE, `${ICONS_TYPE}Prefixed`]

export class Types {
  private _svgs: Map<string, SvgMapObject>
  private _options: Options
  private _root: string

  constructor(
    svgs: Map<string, SvgMapObject>,
    options: Options,
    root: string,
  ) {
    this._svgs = svgs
    this._options = options
    this._root = root
  }

  /**
   * Generate TypeScript type definition string
   * @returns TypeScript type definition content
   */
  public generate(): string {
    if (!this._options.types)
      return ''

    const icons: IconEntry[] = Array.from(this._svgs.values())
      .map(({ id, filePath }) => ({ id, posixPath: normalizePath(filePath) }))
      // Locale-independent sort so the generated file is deterministic across environments.
      .sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0))

    const prefix = this._options.prefix

    const preamble = [
      '// Generated by vite-plugin-svg-spritemap',
      prefix && `export type ${PREFIX_TYPE} = '${prefix}';`,
    ].filter(Boolean).join('\n')

    const blocks = [
      preamble,
      this._declareType(ICONS_TYPE, icons.map(icon => icon.id)),
      ...Object.entries(this._options.types.groups).map(([name, glob]) =>
        this._declareType(name, this._matchIds(icons, glob)),
      ),
    ]

    return `${blocks.join('\n\n')}\n`
  }

  /**
   * Ids of the icons whose file path matches the group glob(s).
   */
  private _matchIds(icons: IconEntry[], glob: Glob): string[] {
    const patterns = (Array.isArray(glob) ? glob : [glob])
      .map(pattern => normalizePath(resolve(this._root, pattern)))
    const isMatch = picomatch(patterns, { dot: true })

    return icons
      .filter(icon => isMatch(icon.posixPath))
      .map(icon => icon.id)
  }

  /**
   * `export type <Name>` (plus `<Name>Prefixed` when a prefix is set).
   * An empty id list resolves to `never`.
   */
  private _declareType(name: string, ids: string[]): string {
    const isEmpty = ids.length === 0
    const union = isEmpty ? 'never' : ids.map(id => `'${id}'`).join(' | ')
    const lines = [`export type ${name} = ${union};`]

    if (this._options.prefix) {
      const prefixed = isEmpty ? 'never' : `\`\${${PREFIX_TYPE}}\${${name}}\``
      lines.push(`export type ${name}Prefixed = ${prefixed};`)
    }

    return lines.join('\n')
  }
}
