import type { Options, SvgMapObject } from '@/types'

export class Types {
  private _svgs: Map<string, SvgMapObject>
  private _options: Options

  constructor(svgs: Map<string, SvgMapObject>, options: Options) {
    this._svgs = svgs
    this._options = options
  }

  /**
   * Generate TypeScript type definition string
   * @returns TypeScript type definition content
   */
  public generate(): string {
    if (!this._options.types)
      return ''

    const iconIds = Array.from(this._svgs.values())
      .map(svg => svg.id)
      .sort()

    if (iconIds.length === 0) {
      return `// Generated by vite-plugin-svg-spritemap
        export type Icons = never;
        export type Prefix = '${this._options.prefix}';
        export type IconsPrefixed = never;
        `
    }

    const unionType = iconIds
      .map(id => `'${id}'`)
      .join(' | ')

    return `// Generated by vite-plugin-svg-spritemap
    export type Icons = ${unionType};
    export type Prefix = '${this._options.prefix}';
    export type IconsPrefixed = \`\${Prefix}\${Icons}\`;
    `
  }
}
