import type { Options, SvgMapObject } from '@/types'

export class Types {
  private _svgs: Map<string, SvgMapObject>
  private _options: Options

  constructor(svgs: Map<string, SvgMapObject>, options: Options) {
    this._svgs = svgs
    this._options = options
  }

  /**
   * Generate TypeScript type definition string
   * @returns TypeScript type definition content
   */
  public generate(): string {
    if (!this._options.types)
      return ''

    const iconIds = Array.from(this._svgs.values())
      .map(svg => svg.id)
      .sort()

    const icons = iconIds.length === 0
      ? 'never'
      : iconIds.map(id => `'${id}'`).join(' | ')

    const lines = [
      '// Generated by vite-plugin-svg-spritemap',
      `export type Icons = ${icons};`,
    ]

    if (this._options.prefix) {
      lines.push(`export type Prefix = '${this._options.prefix}';`)
      lines.push(`export type IconsPrefixed = \`\${Prefix}\${Icons}\`;`)
    }

    return `${lines.join('\n')}\n`
  }
}
